/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProdutoController;
import javax.swing.JOptionPane;
import model.Produto;

/**
 *
 * @author Nicolas Ap
 */
public class GerenciarProdutos extends javax.swing.JFrame {

    /**
     * Creates new form GerenciarProdutos
     */
    public GerenciarProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarProdutos = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        btnAdicionarProdutos = new javax.swing.JButton();
        btnRemoverProdutos = new javax.swing.JButton();
        btnListarProdutos = new javax.swing.JButton();
        txtMostrarId = new javax.swing.JLabel();
        txtBuscarId = new javax.swing.JLabel();
        cmpIdBuscar = new javax.swing.JTextField();
        cmpIdLer = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        cmpNome = new javax.swing.JTextField();
        cmpQuantidade = new javax.swing.JTextField();
        cmpPreco = new javax.swing.JTextField();
        btnEditarProdutos = new javax.swing.JButton();
        txtCategoria = new javax.swing.JLabel();
        cmpCategoria = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Gerenciamento de Produtos");

        btnBuscarProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBuscarProdutos.setText("Buscar Produto");
        btnBuscarProdutos.setPreferredSize(new java.awt.Dimension(129, 23));

        btnLimparCampos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.setPreferredSize(new java.awt.Dimension(129, 23));
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        btnAdicionarProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdicionarProdutos.setText("Adicionar Produto");
        btnAdicionarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarProdutosActionPerformed(evt);
            }
        });

        btnRemoverProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoverProdutos.setText("Remover Produto");
        btnRemoverProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverProdutosActionPerformed(evt);
            }
        });

        btnListarProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnListarProdutos.setText("Listar Produtos");

        txtMostrarId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMostrarId.setText("ID:");

        txtBuscarId.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtBuscarId.setText("ID:");

        cmpIdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpIdBuscarActionPerformed(evt);
            }
        });

        cmpIdLer.setEditable(false);
        cmpIdLer.setBackground(new java.awt.Color(153, 153, 153));
        cmpIdLer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cmpIdLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpIdLerActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.setText("Nome:");

        txtQuantidade.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtQuantidade.setText("Quantidade:");

        txtPreco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPreco.setText("Preço de Venda:");

        cmpNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNomeActionPerformed(evt);
            }
        });

        cmpQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpQuantidadeActionPerformed(evt);
            }
        });

        btnEditarProdutos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEditarProdutos.setText("Editar Produto");

        txtCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCategoria.setText("Categoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionarProdutos)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverProdutos)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtQuantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmpQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(txtPreco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmpPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCategoria)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmpCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmpIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmpIdLer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 248, Short.MAX_VALUE)
                                .addComponent(btnBuscarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtMostrarId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtBuscarId, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(727, 727, 727))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMostrarId)
                    .addComponent(cmpIdBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarId)
                    .addComponent(cmpIdLer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCategoria)
                    .addComponent(cmpCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome)
                    .addComponent(cmpNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade)
                    .addComponent(txtPreco)
                    .addComponent(cmpQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnLimparCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoverProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void cmpIdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpIdBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpIdBuscarActionPerformed

    private void cmpIdLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpIdLerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpIdLerActionPerformed

    private void btnAdicionarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarProdutosActionPerformed
        
        ProdutoController produtoController = new ProdutoController();
        
        try{ 
            
            System.out.println("Valor do campo categoria: '" + cmpCategoria.getText() + "'");
   
            if (cmpNome.getText().isEmpty() || cmpCategoria.getText().isEmpty() || cmpQuantidade.getText().isEmpty() || cmpPreco.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de cadastrar um novo produto!");
                return;
            }
            
            String nome = cmpNome.getText();
            int categoria = Integer.valueOf(cmpCategoria.getText().trim());
            int quantidade = Integer.valueOf(cmpQuantidade.getText().trim());
            double preco = Double.valueOf(cmpPreco.getText().trim());
            
            Produto produto = new Produto(nome, categoria, quantidade, preco);

            produtoController.adicionarProduto(produto);
            
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            limparCampos();

        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Campos numéricos (Categoria, Quantidade, Preço) inválidos!");
        } 
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarProdutosActionPerformed

    private void cmpNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNomeActionPerformed

    private void cmpQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpQuantidadeActionPerformed

    private void btnRemoverProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverProdutosActionPerformed
        
        ProdutoController produtoController = new ProdutoController();
        
        try{
            int idProduto = Integer.parseInt(cmpIdBuscar.getText());
            
            int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja mesmo remover o produto informado?", "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if (confirmacao!=JOptionPane.YES_OPTION){
                return;
            }
            
            produtoController.removerProduto(idProduto);
            JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Informe um ID válido!");
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao remover o produto: " + e.getMessage());
        }
    }//GEN-LAST:event_btnRemoverProdutosActionPerformed

    private void limparCampos(){
        cmpIdBuscar.setText("");
        cmpIdLer.setText("");
        cmpNome.setText("");
        cmpCategoria.setText("");
        cmpQuantidade.setText("");
        cmpPreco.setText("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarProdutos;
    private javax.swing.JButton btnBuscarProdutos;
    private javax.swing.JButton btnEditarProdutos;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnListarProdutos;
    private javax.swing.JButton btnRemoverProdutos;
    private javax.swing.JTextField cmpCategoria;
    private javax.swing.JTextField cmpIdBuscar;
    private javax.swing.JTextField cmpIdLer;
    private javax.swing.JTextField cmpNome;
    private javax.swing.JTextField cmpPreco;
    private javax.swing.JTextField cmpQuantidade;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtBuscarId;
    private javax.swing.JLabel txtCategoria;
    private javax.swing.JLabel txtMostrarId;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtPreco;
    private javax.swing.JLabel txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
